### ISSUE TITLE
Implement model for resources:  cpu , disk, ram, network

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#12]

**Comment by ddpaimon** [comment]
Estimated time: 4h

**Comment by bwsw** [comment]
Why all-in-one, why not specified deliverables?

**Comment by ddpaimon** [comment]
I implement models. 
Interface Resource provides method 'getResult', that return QueryResult from InfluxDB.
This method included Template method 'prepareQuery'.
Each Concrete model (cpu, disk, ram, network) implemnt this Template method, and return specific query.
There are only one test for method 'getResult', because it's common for each models.
Commits:
Cpu impl: https://github.com/bwsw/cs-pulse-server/commit/1614718d9a4b9c896b2bf56ddac811a5d7fc660b
Ram, disk, network impl: https://github.com/bwsw/cs-pulse-server/commit/aca09de5e9ea9ae64ac3b6b467ade23410abb0af
Tests: https://github.com/bwsw/cs-pulse-server/commit/0b70c012addc745c8f36e610efc24e09ad9a1e7a

**Comment by bwsw** [comment]
LGTM
