### ISSUE TITLE
Implement CpuViewFabric, CpuViewMeta, CpuViewData

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#13]
Describe output representation of model: what controller will give for the client.

**Comment by bwsw** [comment]
I don't understand what are deliverables and expectations. Explain, describe, decompose.

**Comment by ddpaimon** [comment]
I did not provide a representation implementation on the class diagram, because I did not have an understanding. Now it is.
You can see Fabric method. We have decomposed this implementation into two tasks: View and ViewFabric
![pulseschema](https://cloud.githubusercontent.com/assets/19563691/26399381/eca11afa-40a6-11e7-983b-b7ba7968aec3.png)

**Comment by ddpaimon** [comment]
View describe output format, without any logic. And Fabric fills View.

**Comment by ddpaimon** [comment]
I think we can decompose by models: CpuViewFabric, CpuViewMeta, CpuViewData - one task, etc.

**Comment by ddpaimon** [comment]
Estimated time: 4h

**Comment by ddpaimon** [comment]
Implemented Cpu View with tests: https://github.com/bwsw/cs-pulse-server/commit/65fe4ae58668ffcb7d86d7c92d809c7c666c5e6b

**Comment by bwsw** [comment]
Look at commit inline comments.

**Comment by bwsw** [comment]
Discussed. Agreed to define additional restrictions for shifts in the config. Agreed to add additional method which can be used to get allowed intervals.
